apply plugin: 'com.android.library'

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        minSdkVersion     rootProject.ext.minSdkVersion
        targetSdkVersion  rootProject.ext.targetSdkVersion
        versionCode 7
        versionName "6.4.7"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions "default"
    productFlavors {
        lite {}
        full {}
        kids {}
    }

    // AGP 8：移除 defaultPublishConfig，必要時改為 publishing { singleVariant("liteDebug") }
    // publishing {
    //     singleVariant("liteDebug")
    // }

    // AGP 8：將 lintOptions 改為 lint 區塊
    lint {
        abortOnError false
        check false
        lintConfig rootProject.file('lint.xml')
    }
}

dependencies {
    androidTestImplementation('androidx.test.espresso:espresso-core:' + rootProject.ext.espressoCoreVersion) {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    testImplementation 'junit:junit:' + rootProject.ext.junitVersion

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:' + rootProject.ext.appCompatXLibraryVersion
    implementation 'com.squareup.okhttp3:okhttp:' + rootProject.ext.okhttpVersion
    implementation 'com.squareup:otto:' + rootProject.ext.ottoVersion
    implementation 'dnsjava:dnsjava:' + rootProject.ext.dnsjavaVersion

    implementation project(path: ':sharedutils')
    implementation project(path: ':common')

    // Crosswalk 已移除（如需請自行還原）
    // liteImplementation 'org.xwalk:xwalk_shared_library:' + rootProject.ext.xwalkSharedLibraryVersion
    // fullImplementation 'org.xwalk:xwalk_core_library:' + rootProject.ext.xwalkCoreLibraryVersion
}
