# Kotlin / JVM
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 
org.gradle.parallel=true
# 打开 Gradle 配置缓存和构建缓存
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.warning.mode=all
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
# Kotlin incremental
kotlin.code.style=official
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process

# 禁止 AGP 访问 JCenter (默认已停用)
# 其他自定义属性可在此添加


