pluginManagement {
  repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
  }
  plugins {
    id("com.android.application") version "8.4.2"
    id("com.android.library") version "8.4.2"
    id("org.jetbrains.kotlin.android") version "1.9.22"
  }
}

rootProject.name = "szzdtv"

// Include Android modules
include ':app'
include ':smartyoutubetv'
include ':browser'
include ':common'
// 已迁移至 Media3，暂时移除 ExoPlayer VP9 扩展模块
// include ':exoplayer-extension-vp9'
include ':exoplayeractivity'
include ':pwaapp'
include ':sharedutils'
