rootProject.name = 'szmjtv'

// Project modules
include ':common'
include ':szmjtv'
include ':pwaapp'   // <-- added mapping for renamed module

// Map new module name to existing directory
project(':szmjtv').projectDir = file('smartyoutubetv')

//  include ':exoplayeractivity'

// If a module lives in a non-default path, map it:
// project(':common').projectDir = file('common')
