apply plugin: 'com.android.application'

android {
    namespace "com.example.tvapp"

    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.szzdmj.szzdtv.pwa"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    // 使用 webserver artifact，它包含 org.nanohttpd.protocols.http 和 response 包
    implementation 'org.nanohttpd:nanohttpd-webserver:2.3.2'
}
