apply plugin: 'com.android.library'

android {
    namespace 'szzdtv.common'
    compileSdk 34

    defaultConfig {
        minSdk 22
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    flavorDimensions "default"
    productFlavors {
        kids { dimension "default" }
        full { dimension "default" }
        lite { dimension "default" }
    }
}

def manifestRelative = 'src/main/AndroidManifest.xml'

tasks.register('generateEmptyManifest') { t ->
    outputs.file("$projectDir/${manifestRelative}")
    doLast {
        def manifestFile = new File(t.project.projectDir, manifestRelative)
        if (!manifestFile.exists()) {
            manifestFile.parentFile.mkdirs()
            manifestFile.text = '''<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="szzdtv.common">
</manifest>'''
            println "Created empty manifest at ${manifestFile}"
        } else {
            println "Manifest already exists at ${manifestFile}"
        }
    }
}

tasks.matching { it.name == 'preBuild' }.configureEach { it.dependsOn tasks.named('generateEmptyManifest') }


