package com.liskovsoft.smartyoutubetv;

/**
 * Minimal BuildConfig stub used at compile time.
 * The real BuildConfig is generated by Gradle; this stub avoids compilation errors in CI.
 */
public final class BuildConfig {
    public static final boolean DEBUG = false;
    private BuildConfig() {}
}
