package com.liskovsoft.smartyoutubetv;

/**
 * Temporary compile-time R stub for smartyoutubetv.
 * - Add only the ids/layouts/dimens/styleable entries referenced by current compile errors.
 * - Remove this file once real resources are present and R is generated by the Android build system.
 */
public final class R {
    public static final class id {
        public static final int bootstrap_checkbox_wrapper = 0x7f010001;
        public static final int bootstrap_checkbox_content = 0x7f010002;
        public static final int bootstrap_checkbox = 0x7f010003;
        public static final int bootstrap_button_wrapper = 0x7f010004;
        public static final int bootstrap_button_content = 0x7f010005;
        public static final int bootstrap_button_image = 0x7f010006;
        public static final int bootstrap_button_text = 0x7f010007;
        public static final int player_view = 0x7f010008;
        public static final int root = 0x7f010009;
    }

    public static final class layout {
        public static final int bootstrap_check_button = 0x7f020001;
        public static final int bootstrap_large_button = 0x7f020002;
        public static final int player_activity = 0x7f020003;
    }

    public static final class dimen {
        public static final int bootstrap_button_text_size = 0x7f030001;
        public static final int bootstrap_text_button_padding = 0x7f030002;
        public static final int bootstrap_large_button_padding = 0x7f030003;
    }

    public static final class styleable {
        // Minimal placeholders for styleable arrays referenced in code.
        public static final int[] BootstrapCheckButton = { 0x01010000, 0x01010001 };
        public static final int BootstrapCheckButton_titleText = 0;
        public static final int BootstrapCheckButton_onCheckedChanged = 1;

        public static final int[] BootstrapLargeButton = { 0x01010002, 0x01010003 };
        public static final int BootstrapLargeButton_mainIcon = 0;
        public static final int BootstrapLargeButton_titleText = 1;
    }
}
