apply plugin: 'com.android.application'

println "DIAG(app flavors restored): orig beta kids Vlive Vbolshoetv Vbolshoetv2 Vrtarmenia2 Vredboxtv"

android {
    // Java 8 for default interface methods
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
    testOptions.unitTests.includeAndroidResources = true

    defaultConfig {
        minSdkVersion     rootProject.ext.minSdkVersion
        targetSdkVersion  rootProject.ext.targetSdkVersion
        applicationId "com.liskovsoft.videomanager"
        versionCode 1319
        versionName "6.17.739"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    buildTypes {
        debug {
            buildConfigField "boolean", "CRASHLYTICS_ENABLED", "false"
        }
        release {
            buildConfigField "boolean", "CRASHLYTICS_ENABLED", "false"
            debuggable false
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions "default"
    productFlavors {
        lite { }
        full { }
        orig       { matchingFallbacks = ['lite'] }
        beta       { matchingFallbacks = ['lite']; applicationIdSuffix ".beta" }
        kids       { matchingFallbacks = ['kids','lite']; applicationIdSuffix ".kids" }
        Vlive      { matchingFallbacks = ['lite']; applicationIdSuffix ".live" }
        Vbolshoetv { matchingFallbacks = ['lite']; versionCode 9400 + defaultConfig.versionCode }
        Vbolshoetv2 {
            matchingFallbacks = ['full']
            versionCode 9400 + defaultConfig.versionCode
        }
        Vrtarmenia2 {
            matchingFallbacks = ['lite']
            versionCode 9400 + defaultConfig.versionCode
            applicationId "com.google.android.youtube.tv"
        }
        Vredboxtv {
            matchingFallbacks = ['lite']
            versionCode 9400 + defaultConfig.versionCode
            applicationId "com.redboxtv.smartyoutubetv"
        }
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    // Tests
    androidTestImplementation('androidx.test.espresso:espresso-core:' + rootProject.ext.espressoCoreVersion)
    testImplementation 'junit:junit:'              + rootProject.ext.junitVersion
    testImplementation 'org.assertj:assertj-core:' + rootProject.ext.assertJVersion
    testImplementation 'org.robolectric:robolectric:' + rootProject.ext.robolectricVersion
    testImplementation 'commons-io:commons-io:'    + rootProject.ext.commonsIOVersion

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Internal modules
    implementation     project(':sharedutils')
    implementation     project(':common')
    implementation     project(':browser')
    implementation     project(':exoplayeractivity')

    // UI / AndroidX
    implementation 'androidx.appcompat:appcompat:'           + rootProject.ext.appCompatXLibraryVersion
    implementation 'androidx.media:media:'                   + rootProject.ext.appCompatXLibraryVersion
    implementation 'androidx.recyclerview:recyclerview:'     + rootProject.ext.appCompatXLibraryVersion
    implementation 'androidx.constraintlayout:constraintlayout:' + rootProject.ext.constraintLayoutXVersion

    // JSON / parsing
    implementation 'com.google.code.gson:gson:'              + rootProject.ext.gsonVersion
    implementation 'com.jayway.jsonpath:json-path:'          + rootProject.ext.jsonPathVersion

    // Local HTTP / voice overlay
    implementation 'org.nanohttpd:nanohttpd:'                + rootProject.ext.nanoHttpdVersion
    implementation 'com.algolia.instantsearch:voice:'        + rootProject.ext.voiceOverlayVersion

    // Network / event bus
    implementation 'com.squareup.okhttp3:okhttp:'            + rootProject.ext.okhttpVersion
    implementation 'com.squareup:otto:'                      + rootProject.ext.ottoVersion

    // Disk cache & misc
    implementation 'com.jakewharton:disklrucache:'           + rootProject.ext.diskLruCacheVersion
    implementation 'org.apache.commons:commons-lang3:'       + rootProject.ext.apacheCommonsLangVersion

    // Multidex (legacy support if needed)
    implementation 'androidx.multidex:multidex:'           + rootProject.ext.multiDexVersion
}
